// Date: 23/05/2012 18:44:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelBear extends ModelBase
{
  //fields
    ModelRenderer ear1;
    ModelRenderer ear2;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer body1;
    ModelRenderer Leg4;
    ModelRenderer Leg3;
    ModelRenderer Leg2;
    ModelRenderer Leg1;
  
  public ModelBear()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      ear1 = new ModelRenderer(this, 44, 0);
      ear1.addBox(0F, 0F, 0F, 2, 2, 1);
      ear1.setRotationPoint(-2.5F, 2F, -6.533333F);
      ear1.setTextureSize(64, 32);
      ear1.mirror = true;
      setRotation(ear1, 0F, 0.1745329F, -0.0872665F);
      ear2 = new ModelRenderer(this, 44, 0);
      ear2.addBox(0F, 0F, 0F, 2, 2, 1);
      ear2.setRotationPoint(4.5F, 2F, -7F);
      ear2.setTextureSize(64, 32);
      ear2.mirror = true;
      setRotation(ear2, 0F, -0.1745329F, 0.0872665F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 7, 7, 7);
      Head.setRotationPoint(-1.5F, 4F, -11F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0.063722F, 0F, 0F);
      Nose = new ModelRenderer(this, 28, 0);
      Nose.addBox(0F, 0F, 0F, 4, 3, 6);
      Nose.setRotationPoint(0F, 7F, -14F);
      Nose.setTextureSize(64, 32);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      body1 = new ModelRenderer(this, 0, 14);
      body1.addBox(-6F, 0F, -4F, 12, 19, 13);
      body1.setRotationPoint(2F, 11F, -5F);
      body1.setTextureSize(64, 32);
      body1.mirror = true;
      setRotation(body1, 1.570796F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 46);
      Leg4.addBox(0F, 0F, 0F, 4, 10, 4);
      Leg4.setRotationPoint(-4F, 14F, 10F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 46);
      Leg3.addBox(0F, 0F, 0F, 4, 10, 4);
      Leg3.setRotationPoint(4F, 14F, 10F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 46);
      Leg2.addBox(0F, 0F, 0F, 4, 10, 4);
      Leg2.setRotationPoint(4F, 14F, -4F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 46);
      Leg1.addBox(0F, 0F, 0F, 4, 10, 4);
      Leg1.setRotationPoint(-4F, 14F, -4F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ear1.render(f5);
    ear2.render(f5);
    Head.render(f5);
    Nose.render(f5);
    body1.render(f5);
    Leg4.render(f5);
    Leg3.render(f5);
    Leg2.render(f5);
    Leg1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
