// Date: 23/05/2012 15:57:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelDeer extends ModelBase
{
  //fields
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer body;
    ModelRenderer tail;
    ModelRenderer neck;
    ModelRenderer head;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
  
  public ModelDeer()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      leg1 = new ModelRenderer(this, 0, 33);
      leg1.addBox(0F, 0F, 0F, 4, 10, 4);
      leg1.setRotationPoint(-4.5F, 14F, -1F);
      leg1.setTextureSize(128, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 33);
      leg2.addBox(0F, 0F, 0F, 4, 10, 4);
      leg2.setRotationPoint(1.5F, 14F, 15.5F);
      leg2.setTextureSize(128, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 33);
      leg3.addBox(0F, 0F, 0F, 4, 10, 4);
      leg3.setRotationPoint(-4.5F, 14F, 15.5F);
      leg3.setTextureSize(128, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 33);
      leg4.addBox(0F, 0F, 0F, 4, 10, 4);
      leg4.setRotationPoint(1.5F, 14F, -1F);
      leg4.setTextureSize(128, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      body = new ModelRenderer(this, 9, 0);
      body.addBox(0F, 0F, 0F, 10, 10, 21);
      body.setRotationPoint(-4.5F, 4F, -1.5F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 18, 33);
      tail.addBox(0F, 0F, 0F, 3, 2, 5);
      tail.setRotationPoint(-1F, 5F, 18F);
      tail.setTextureSize(128, 64);
      tail.mirror = true;
      setRotation(tail, 0.8922867F, 0F, 0F);
      neck = new ModelRenderer(this, 55, 0);
      neck.addBox(0F, -11F, 0F, 4, 11, 4);
      neck.setRotationPoint(-1.5F, 7F, -1F);
      neck.setTextureSize(128, 64);
      neck.mirror = true;
      setRotation(neck, 0.5576792F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(1F, 0F, -8F, 5, 5, 9);
      head.setRotationPoint(-3.033333F, -5F, -3F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0.1487144F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 0, 0);
      Ear1.addBox(0F, 0F, 0F, 2, 2, 1);
      Ear1.setRotationPoint(-2F, -6F, -4F);
      Ear1.setTextureSize(128, 64);
      Ear1.mirror = true;
      setRotation(Ear1, 0.122173F, -0.2094395F, 0F);
      Ear2 = new ModelRenderer(this, 0, 0);
      Ear2.addBox(-2F, 0F, 0F, 2, 2, 1);
      Ear2.setRotationPoint(3F, -6F, -4F);
      Ear2.setTextureSize(128, 64);
      Ear2.mirror = true;
      setRotation(Ear2, 0.122173F, 0.2094395F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    body.render(f5);
    tail.render(f5);
    neck.render(f5);
    head.render(f5);
    Ear1.render(f5);
    Ear2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
