// Date: 23/05/2012 15:59:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelElk extends ModelBase
{
  //fields
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer body;
    ModelRenderer tail;
    ModelRenderer neck;
    ModelRenderer head;
    ModelRenderer horn1;
    ModelRenderer horn2;
    ModelRenderer horn3;
    ModelRenderer horn4;
    ModelRenderer horn5;
    ModelRenderer horn1;
    ModelRenderer horn2;
    ModelRenderer horn5;
    ModelRenderer horn4;
    ModelRenderer horn3;
  
  public ModelElk()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      leg1 = new ModelRenderer(this, 0, 33);
      leg1.addBox(0F, 0F, 0F, 4, 12, 4);
      leg1.setRotationPoint(-5F, 12F, -1F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 33);
      leg2.addBox(0F, 0F, 0F, 4, 12, 4);
      leg2.setRotationPoint(2F, 12F, 16.5F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 33);
      leg3.addBox(0F, 0F, 0F, 4, 12, 4);
      leg3.setRotationPoint(-5F, 12F, 16.5F);
      leg3.setTextureSize(64, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 33);
      leg4.addBox(0F, 0F, 0F, 4, 12, 4);
      leg4.setRotationPoint(2F, 12F, -1F);
      leg4.setTextureSize(64, 32);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      body = new ModelRenderer(this, 7, 0);
      body.addBox(0F, 0F, 0F, 11, 10, 22);
      body.setRotationPoint(-5F, 2F, -1.5F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 17, 33);
      tail.addBox(0F, 0F, 0F, 3, 2, 5);
      tail.setRotationPoint(-1F, 3F, 19F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      setRotation(tail, 0.8922867F, 0F, 0F);
      neck = new ModelRenderer(this, 53, 0);
      neck.addBox(0F, -11F, 0F, 4, 11, 4);
      neck.setRotationPoint(-1.5F, 5F, -1F);
      neck.setTextureSize(64, 32);
      neck.mirror = true;
      setRotation(neck, 0.5576792F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(1F, 0F, -8F, 5, 5, 9);
      head.setRotationPoint(-3.033333F, -7F, -3F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0.1487144F, 0F, 0F);
      horn1 = new ModelRenderer(this, 0, 15);
      horn1.addBox(0F, -5F, 0F, 1, 5, 1);
      horn1.setRotationPoint(2F, -6F, -4F);
      horn1.setTextureSize(64, 32);
      horn1.mirror = true;
      setRotation(horn1, 0F, 0.0743572F, 1.152537F);
      horn2 = new ModelRenderer(this, 0, 15);
      horn2.addBox(0F, -5F, 0F, 1, 5, 1);
      horn2.setRotationPoint(6F, -8F, -4F);
      horn2.setTextureSize(64, 32);
      horn2.mirror = true;
      setRotation(horn2, 0F, 0.4833219F, 1.07818F);
      horn3 = new ModelRenderer(this, 0, 15);
      horn3.addBox(0F, 0F, 0F, 1, 4, 1);
      horn3.setRotationPoint(11F, -10F, -5F);
      horn3.setTextureSize(64, 32);
      horn3.mirror = true;
      setRotation(horn3, 0F, -1.412787F, 2.13777F);
      horn4 = new ModelRenderer(this, 0, 15);
      horn4.addBox(0F, 0F, 0F, 1, 4, 1);
      horn4.setRotationPoint(7F, -8F, -4F);
      horn4.setTextureSize(64, 32);
      horn4.mirror = true;
      setRotation(horn4, 0F, -1.412787F, 2.13777F);
      horn5 = new ModelRenderer(this, 0, 15);
      horn5.addBox(0F, 0F, 0F, 1, 4, 1);
      horn5.setRotationPoint(4F, -6.5F, -3F);
      horn5.setTextureSize(64, 32);
      horn5.mirror = true;
      setRotation(horn5, 0F, -1.412787F, 2.13777F);
      horn1 = new ModelRenderer(this, 0, 15);
      horn1.addBox(-1F, -5F, 0F, 1, 5, 1);
      horn1.setRotationPoint(-1F, -6F, -4F);
      horn1.setTextureSize(64, 32);
      horn1.mirror = true;
      setRotation(horn1, 0F, -0.074351F, -1.152546F);
      horn2 = new ModelRenderer(this, 0, 15);
      horn2.addBox(-1F, -5F, 0F, 1, 5, 1);
      horn2.setRotationPoint(-5F, -8F, -4F);
      horn2.setTextureSize(64, 32);
      horn2.mirror = true;
      setRotation(horn2, 0F, -0.4833166F, -1.078177F);
      horn5 = new ModelRenderer(this, 0, 15);
      horn5.addBox(-1F, 0F, 0F, 1, 4, 1);
      horn5.setRotationPoint(-3F, -6.5F, -3F);
      horn5.setTextureSize(64, 32);
      horn5.mirror = true;
      setRotation(horn5, 0F, 1.412792F, -2.137767F);
      horn4 = new ModelRenderer(this, 0, 15);
      horn4.addBox(-1F, 0F, 0F, 1, 4, 1);
      horn4.setRotationPoint(-6F, -8F, -4F);
      horn4.setTextureSize(64, 32);
      horn4.mirror = true;
      setRotation(horn4, 0F, 1.412792F, -2.144748F);
      horn3 = new ModelRenderer(this, 0, 15);
      horn3.addBox(-1F, 0F, 0F, 1, 4, 1);
      horn3.setRotationPoint(-10F, -10F, -5F);
      horn3.setTextureSize(64, 32);
      horn3.mirror = true;
      setRotation(horn3, 0F, 1.412792F, -2.137767F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    body.render(f5);
    tail.render(f5);
    neck.render(f5);
    head.render(f5);
    horn1.render(f5);
    horn2.render(f5);
    horn3.render(f5);
    horn4.render(f5);
    horn5.render(f5);
    horn1.render(f5);
    horn2.render(f5);
    horn5.render(f5);
    horn4.render(f5);
    horn3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
