// Date: 23/05/2012 17:10:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelFox extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer tail;
    ModelRenderer head;
    ModelRenderer nose;
    ModelRenderer ear1;
    ModelRenderer ear2;
  
  public ModelFox()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      body = new ModelRenderer(this, 0, 10);
      body.addBox(0F, 0F, 0F, 6, 6, 12);
      body.setRotationPoint(0F, 12F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 19, 0);
      leg1.addBox(0F, 0F, 0F, 2, 6, 2);
      leg1.setRotationPoint(0F, 18F, 0F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 19, 0);
      leg2.addBox(0F, 0F, 0F, 2, 6, 2);
      leg2.setRotationPoint(4F, 18F, 0F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 19, 0);
      leg3.addBox(0F, 0F, 0F, 2, 6, 2);
      leg3.setRotationPoint(0F, 18F, 10F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 19, 0);
      leg4.addBox(-1F, 0F, 0F, 2, 6, 2);
      leg4.setRotationPoint(5F, 18F, 10F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 26, 10);
      tail.addBox(0F, 0F, 0F, 2, 6, 2);
      tail.setRotationPoint(2F, 14F, 10.53333F);
      tail.setTextureSize(64, 64);
      tail.mirror = true;
      setRotation(tail, 0.5934119F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(0F, 0F, 0F, 5, 5, 4);
      head.setRotationPoint(0.5F, 10F, -3F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 0, 15);
      nose.addBox(0F, 0F, 0F, 2, 2, 3);
      nose.setRotationPoint(2F, 13F, -5F);
      nose.setTextureSize(64, 64);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      ear1 = new ModelRenderer(this, 0, 10);
      ear1.addBox(0F, 0F, 0F, 2, 3, 1);
      ear1.setRotationPoint(0F, 8F, -1F);
      ear1.setTextureSize(64, 64);
      ear1.mirror = true;
      setRotation(ear1, 0F, -0.1745329F, 0F);
      ear2 = new ModelRenderer(this, 0, 10);
      ear2.addBox(-2F, 0F, 0F, 2, 3, 1);
      ear2.setRotationPoint(6F, 8F, -1F);
      ear2.setTextureSize(64, 64);
      ear2.mirror = true;
      setRotation(ear2, 0F, 0.1745329F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    tail.render(f5);
    head.render(f5);
    nose.render(f5);
    ear1.render(f5);
    ear2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
