// Date: 9/04/2012 20:27:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
  
  public ModelNew()
  {
    textureWidth = 112;
    textureHeight = 96;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 16, 16, 16);
      head.setRotationPoint(-4F, -31F, -2F);
      head.setTextureSize(112, 96);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 32, 32);
      body.addBox(-4F, 0F, -2F, 16, 24, 8);
      body.setRotationPoint(-4F, -24F, 0F);
      body.setTextureSize(112, 96);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 80, 32);
      rightarm.addBox(-3F, -2F, -2F, 8, 24, 8);
      rightarm.setRotationPoint(-13F, -21F, 0F);
      rightarm.setTextureSize(112, 96);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 80, 32);
      leftarm.addBox(-1F, -2F, -2F, 8, 24, 8);
      leftarm.setRotationPoint(9F, -22F, 0F);
      leftarm.setTextureSize(112, 96);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 32);
      rightleg.addBox(-2F, 0F, -2F, 8, 24, 8);
      rightleg.setRotationPoint(-6F, 0F, 0F);
      rightleg.setTextureSize(112, 96);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 64);
      leftleg.addBox(-2F, 0F, -2F, 8, 24, 8);
      leftleg.setRotationPoint(2F, 0F, 0F);
      leftleg.setTextureSize(112, 96);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
