// Date: 23/05/2012 19:29:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelGoat extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer tail;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer neck;
    ModelRenderer head;
    ModelRenderer nose;
    ModelRenderer mounth;
    ModelRenderer ear1;
    ModelRenderer ear2;
    ModelRenderer beard;
    ModelRenderer hornleft1;
    ModelRenderer Hornleft2;
    ModelRenderer Hornleft3;
    ModelRenderer Hornright1;
    ModelRenderer Hornright2;
    ModelRenderer Hornright3;
  
  public ModelGoat()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      body = new ModelRenderer(this, 16, 0);
      body.addBox(0F, 0F, 0F, 7, 8, 16);
      body.setRotationPoint(-3F, 8F, -6F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 52, 0);
      tail.addBox(0F, 0F, 0F, 3, 4, 2);
      tail.setRotationPoint(-1F, 5F, 9F);
      tail.setTextureSize(128, 64);
      tail.mirror = true;
      setRotation(tail, -0.296706F, 0F, 0F);
      leg1 = new ModelRenderer(this, 16, 25);
      leg1.addBox(1F, 0F, 0F, 2, 8, 2);
      leg1.setRotationPoint(-2.5F, 16F, -5F);
      leg1.setTextureSize(128, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 16, 25);
      leg2.addBox(0F, 0F, 0F, 2, 8, 2);
      leg2.setRotationPoint(1.5F, 16F, -5F);
      leg2.setTextureSize(128, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 16, 25);
      leg3.addBox(0F, 0F, 0F, 2, 8, 2);
      leg3.setRotationPoint(1.5F, 16F, 8F);
      leg3.setTextureSize(128, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 16, 25);
      leg4.addBox(0F, 0F, 0F, 2, 8, 2);
      leg4.setRotationPoint(-2.5F, 16F, 8F);
      leg4.setTextureSize(128, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 0, 25);
      neck.addBox(0F, 0F, 0F, 3, 6, 4);
      neck.setRotationPoint(-1F, 10F, -10F);
      neck.setTextureSize(128, 64);
      neck.mirror = true;
      setRotation(neck, 1.054014F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(0F, 0F, 0F, 4, 5, 4);
      head.setRotationPoint(-1.5F, 5F, -11F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 0, 10);
      nose.addBox(0F, 0F, 0F, 3, 3, 3);
      nose.setRotationPoint(-1F, 6.366667F, -14F);
      nose.setTextureSize(128, 64);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      mounth = new ModelRenderer(this, -1, 17);
      mounth.addBox(0F, 0F, 0F, 2, 1, 3);
      mounth.setRotationPoint(-0.5F, 9F, -13.5F);
      mounth.setTextureSize(128, 64);
      mounth.mirror = true;
      setRotation(mounth, 0F, 0F, 0F);
      ear1 = new ModelRenderer(this, 0, 22);
      ear1.addBox(0F, 0F, 0F, 3, 1, 1);
      ear1.setRotationPoint(2F, 6F, -9F);
      ear1.setTextureSize(128, 64);
      ear1.mirror = true;
      setRotation(ear1, 0F, -0.2617994F, 0F);
      ear2 = new ModelRenderer(this, 0, 22);
      ear2.addBox(-3F, 0F, 0F, 3, 1, 1);
      ear2.setRotationPoint(-1F, 6F, -9F);
      ear2.setTextureSize(128, 64);
      ear2.mirror = true;
      setRotation(ear2, 0F, 0.2617994F, 0F);
      beard = new ModelRenderer(this, 10, 17);
      beard.addBox(0F, 2F, 0F, 1, 2, 1);
      beard.setRotationPoint(0F, 8F, -13.33333F);
      beard.setTextureSize(128, 64);
      beard.mirror = true;
      setRotation(beard, 0F, 0F, 0F);
      hornleft1 = new ModelRenderer(this, 18, 0);
      hornleft1.addBox(0F, 0F, 0F, 2, 2, 2);
      hornleft1.setRotationPoint(1F, 4F, -8.6F);
      hornleft1.setTextureSize(128, 64);
      hornleft1.mirror = true;
      setRotation(hornleft1, 0F, 0F, 0F);
      Hornleft2 = new ModelRenderer(this, 18, 5);
      Hornleft2.addBox(1F, 0F, 0F, 4, 2, 1);
      Hornleft2.setRotationPoint(2F, 3.966667F, -8F);
      Hornleft2.setTextureSize(128, 64);
      Hornleft2.mirror = true;
      setRotation(Hornleft2, 0F, -0.4712389F, 0.296706F);
      Hornleft3 = new ModelRenderer(this, 18, 9);
      Hornleft3.addBox(0F, 0F, 0F, 1, 4, 1);
      Hornleft3.setRotationPoint(5.533333F, 3F, -4.6F);
      Hornleft3.setTextureSize(128, 64);
      Hornleft3.mirror = true;
      setRotation(Hornleft3, -0.3839724F, 0F, 0.2617994F);
      Hornright1 = new ModelRenderer(this, 18, 0);
      Hornright1.addBox(0F, 0F, 0F, 2, 2, 2);
      Hornright1.setRotationPoint(-2F, 4F, -8.6F);
      Hornright1.setTextureSize(128, 64);
      Hornright1.mirror = true;
      setRotation(Hornright1, 0F, 0F, 0F);
      Hornright2 = new ModelRenderer(this, 18, 5);
      Hornright2.addBox(-5F, 0F, 0F, 4, 2, 1);
      Hornright2.setRotationPoint(-1F, 4F, -8F);
      Hornright2.setTextureSize(128, 64);
      Hornright2.mirror = true;
      setRotation(Hornright2, 0F, 0.4712389F, -0.296706F);
      Hornright3 = new ModelRenderer(this, 18, 9);
      Hornright3.addBox(-1F, 0F, 0F, 1, 4, 1);
      Hornright3.setRotationPoint(-4.5F, 3F, -4.6F);
      Hornright3.setTextureSize(128, 64);
      Hornright3.mirror = true;
      setRotation(Hornright3, -0.3839724F, 0F, -0.2617994F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    tail.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    neck.render(f5);
    head.render(f5);
    nose.render(f5);
    mounth.render(f5);
    ear1.render(f5);
    ear2.render(f5);
    beard.render(f5);
    hornleft1.render(f5);
    Hornleft2.render(f5);
    Hornleft3.render(f5);
    Hornright1.render(f5);
    Hornright2.render(f5);
    Hornright3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
