// Date: 23/05/2012 16:26:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelSabreCat extends ModelBase
{
  //fields
    ModelRenderer ear1;
    ModelRenderer ear2;
    ModelRenderer tooth1;
    ModelRenderer tooth2;
    ModelRenderer Head;
    ModelRenderer Nose;
    ModelRenderer Mouth;
    ModelRenderer body1;
    ModelRenderer Body2;
    ModelRenderer Tail;
    ModelRenderer Leg4;
    ModelRenderer Leg3;
    ModelRenderer Leg2;
    ModelRenderer Leg1;
  
  public ModelSabreCat()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      ear1 = new ModelRenderer(this, 26, 0);
      ear1.addBox(0F, 0F, 0F, 3, 3, 1);
      ear1.setRotationPoint(-3F, 3F, -6.533333F);
      ear1.setTextureSize(64, 32);
      ear1.mirror = true;
      setRotation(ear1, 0F, 0.1745329F, -0.0872665F);
      ear2 = new ModelRenderer(this, 26, 0);
      ear2.addBox(0F, 0F, 0F, 3, 3, 1);
      ear2.setRotationPoint(5F, 3F, -7F);
      ear2.setTextureSize(64, 32);
      ear2.mirror = true;
      setRotation(ear2, 0F, -0.1745329F, 0.0872665F);
      tooth1 = new ModelRenderer(this, 0, 0);
      tooth1.addBox(0F, 0F, 0F, 1, 3, 1);
      tooth1.setRotationPoint(3F, 10.53333F, -14F);
      tooth1.setTextureSize(64, 32);
      tooth1.mirror = true;
      setRotation(tooth1, 0.2094395F, 0F, 0F);
      tooth2 = new ModelRenderer(this, 0, 0);
      tooth2.addBox(0F, 0F, 0F, 1, 3, 1);
      tooth2.setRotationPoint(0F, 10.46667F, -14F);
      tooth2.setTextureSize(64, 32);
      tooth2.mirror = true;
      setRotation(tooth2, 0.2094395F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 8, 8, 8);
      Head.setRotationPoint(-2F, 5F, -10F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0.063722F, 0F, 0F);
      Nose = new ModelRenderer(this, 33, 0);
      Nose.addBox(0F, 0F, 0F, 4, 3, 6);
      Nose.setRotationPoint(0F, 8F, -14F);
      Nose.setTextureSize(64, 32);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      Mouth = new ModelRenderer(this, 54, 0);
      Mouth.addBox(0F, 0F, 0F, 4, 2, 6);
      Mouth.setRotationPoint(0F, 11.53333F, -12.53333F);
      Mouth.setTextureSize(64, 32);
      Mouth.mirror = true;
      setRotation(Mouth, 0.1919862F, 0F, 0F);
      body1 = new ModelRenderer(this, 0, 17);
      body1.addBox(-6F, 0F, -4F, 13, 11, 13);
      body1.setRotationPoint(2F, 11F, -5F);
      body1.setTextureSize(64, 32);
      body1.mirror = true;
      setRotation(body1, 1.570796F, 0F, 0F);
      Body2 = new ModelRenderer(this, 53, 17);
      Body2.addBox(0F, 0F, 0F, 9, 14, 10);
      Body2.setRotationPoint(-2F, 14F, 5F);
      Body2.setTextureSize(64, 32);
      Body2.mirror = true;
      setRotation(Body2, 1.570796F, 0F, 0F);
      Tail = new ModelRenderer(this, 75, 0);
      Tail.addBox(0F, 0F, 0F, 4, 11, 3);
      Tail.setRotationPoint(0F, 7F, 16F);
      Tail.setTextureSize(64, 32);
      Tail.mirror = true;
      setRotation(Tail, 0.7211002F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 42);
      Leg4.addBox(0F, 0F, 0F, 4, 12, 4);
      Leg4.setRotationPoint(-2.466667F, 12F, 14F);
      Leg4.setTextureSize(64, 32);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 42);
      Leg3.addBox(0F, 0F, 0F, 4, 12, 4);
      Leg3.setRotationPoint(3.466667F, 12F, 14F);
      Leg3.setTextureSize(64, 32);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 42);
      Leg2.addBox(0F, 0F, 0F, 4, 11, 4);
      Leg2.setRotationPoint(3.466667F, 13F, -3F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 42);
      Leg1.addBox(0F, 0F, 0F, 4, 11, 4);
      Leg1.setRotationPoint(-2.533333F, 13F, -3F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ear1.render(f5);
    ear2.render(f5);
    tooth1.render(f5);
    tooth2.render(f5);
    Head.render(f5);
    Nose.render(f5);
    Mouth.render(f5);
    body1.render(f5);
    Body2.render(f5);
    Tail.render(f5);
    Leg4.render(f5);
    Leg3.render(f5);
    Leg2.render(f5);
    Leg1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
